"""
Game Settings and Configuration
Centralized configuration for the A3 Yasuo game project.
"""

# Display settings
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60
FULLSCREEN = False
SCALE_FACTOR = 4 # need to scale because our backgrounds have size 320x180 => Scale 4 times
TILE_SIZE_RAW = 24
TILE_SIZE = TILE_SIZE_RAW * SCALE_FACTOR # this is the standard unit we use to do other works later
# so we have 7.5 rows => ceil to 8 rows. 7 full rows and 1/2 the last row.
SOLID_TILES = ['(', '-', ')', '[', '=', ']', '0', '1', '2', '3', '4', '5', '6', '7', '8']

# Game settings
GAME_TITLE = "Yasuo Game"

# Asset paths
ASSETS_PATH = "assets"
NPC_PATH = "assets/NPC"
PLAYER_PATH = "assets/Player"
MAP_PATH = "assets/Map"
SKILLS_PATH = "assets/Skills"


# NPC Settings
NPC_GHOST_HEALTH = 50
NPC_GHOST_DAMAGE = 10
NPC_GHOST_ATTACK_RANGE = 100
NPC_GHOST_SPEED = 2
NPC_GHOST_DETECTION_RANGE = 260
NPC_GHOST_PATROL_RADIUS = 160
NPC_GHOST_ATTACK_COOLDOWN = 60  # frames
NPC_GHOST_PROJECTILE_SPEED = 8

NPC_SHOOTER_HEALTH = 75
NPC_SHOOTER_DAMAGE = 5
NPC_SHOOTER_ATTACK_RANGE = 200
NPC_SHOOTER_SPEED = 1.5
NPC_SHOOTER_DETECTION_RANGE = 400
NPC_SHOOTER_PATROL_RADIUS = 150
NPC_SHOOTER_ATTACK_COOLDOWN = 40  # frames
NPC_SHOOTER_PROJECTILE_SPEED = 12

NPC_ONRE_HEALTH = 100
NPC_ONRE_DAMAGE = 8
NPC_ONRE_ATTACK_RANGE = 50
NPC_ONRE_SPEED = 2.5
NPC_ONRE_DETECTION_RANGE = 200
NPC_ONRE_PATROL_RADIUS = 140
NPC_ONRE_ATTACK_COOLDOWN = 40  # frames


# Boss Settings
BOSS_HEALTH = 3000
BOSS_SPEED = 10

BOSS_MELEE_DAMAGE = 25
BOSS_MELEE_RANGE = 300
BOSS_MELEE_COOLDOWN = 45
BOSS_MELEE_HIT_FRAME = 2

BOSS_RANGED_DAMAGE = 15
BOSS_PROJECTILE_SPEED = 15
BOSS_RANGED_COOLDOWN = 60

BOSS_LASER_DAMAGE = 40
BOSS_LASER_WIDTH = 1500
BOSS_LASER_HEIGHT = 100
BOSS_METEOR_DAMAGE = 80
BOSS_SKILL_COOLDOWN = 600 

# Boss Circular Shooting Skill Settings
CIRCULAR_CHARGE_DURATION = 60
CIRCULAR_SHOOT_DURATION = 180
CIRCULAR_PROJECTILES_PER_STREAM = 12
CIRCULAR_VELOCITY_MULTIPLIER = 0.6

# Boss Meteor Skill Settings
METEOR_CHARGE_DURATION = 60
METEOR_DURATION = 180
METEOR_SPAWN_INTERVAL = 15
METEOR_SIZE_WIDTH = 128
METEOR_SIZE_HEIGHT = 72
METEOR_EXPLOSION_SIZE = 128
METEOR_VELOCITY_X_MIN = -6 
METEOR_VELOCITY_X_MAX = -2
METEOR_VELOCITY_Y_MIN = 8
METEOR_VELOCITY_Y_MAX = 12
METEOR_GROUND_Y = 400

# Boss Summon Minions Skill Settings
SUMMON_CHARGE_DURATION = 60
SUMMON_WAIT_DURATION = 30

# Boss Minion Settings
BOSS_MINION_SIZE = 96
BOSS_MINION_HEALTH_BASE = 80
BOSS_MINION_SPEED = 3
BOSS_MINION_DETECTION_RANGE = 1000
BOSS_MINION_ATTACK_RANGE = 150
BOSS_MINION_ATTACK_COOLDOWN = 90
BOSS_MINION_DAMAGE = 8
BOSS_MINION_FIREBALL_SPEED = 10
BOSS_MINION_FIREBALL_SIZE = 32


# Player Settings
PLAYER_HEALTH = 200
PLAYER_SPEED_WALK = 200
PLAYER_SPEED_RUN = 300
PLAYER_JUMP_POWER = 12
PLAYER_MAX_JUMPS = 1  # Single jump

# Combat Settings
ATTACK_COOLDOWN = 30
SKILL_Q_COOLDOWN = 120
SKILL_W_COOLDOWN = 180
SKILL_E_COOLDOWN = 1

# Damage Settings [MỚI]
PLAYER_ATTACK_DAMAGE = 25
DAMAGE_NORMAL = 20
DAMAGE_SKILL_E = 50
DAMAGE_SKILL_Q = 500
DAMAGE_SKILL_W = 30 

# Block Settings [MỚI]
BLOCK_DAMAGE_REDUCTION = 0.9
BLOCK_STAMINA_COST_PER_HIT = 20

# Player Stats (Refactored for Spec)
PLAYER_MAX_HEALTH = 2000
PLAYER_MAX_STAMINA = 10000

PLAYER_STAMINA_REGEN_WALK = 0.5  # Hồi nội năng khi đi bộ
PLAYER_HEALTH_REGEN = 0.02      # Hồi máu tự nhiên (nếu có)

PLAYER_RUN_COST = 0.2           # Chạy tốn stamina
SKILL_Q_COST = 20
SKILL_W_COST = 30
SKILL_E_COST = 15
PLAYER_HURT_DURATION = 0.5 # Thời gian hiệu ứng Hurt
PLAYER_HITS_TO_STAGGER = 10 # Số lần bị đánh để kích hoạt Hurt stun

# Mechanisms
PLAYER_LIFESTEAL = 100          # Hút máu toàn phần (100%)

# Cơ chế thưởng (Reward)
Reward_Hit_Stamina = 5
Reward_Kill_Stamina = 30

# Physics
GRAVITY = 0.5
MAX_FALL_SPEED = 10
GROUND_Y = 480 # Mức đất tạm thời để test di chuyển (Row 5-6 * 96)

# Colors (R, G, B, A)
COLOR_BLACK = (0, 0, 0, 255)
COLOR_WHITE = (255, 255, 255, 255)
COLOR_RED = (255, 0, 0, 255)
COLOR_GREEN = (0, 255, 0, 255)
COLOR_BLUE = (0, 0, 255, 255)
COLOR_BACKGROUND = (20, 20, 30, 255)

# BOX SETTINGS
BOX_WIDTH = 44
BOX_HEIGHT = 44

# OPEN_COLLECTING_INTERVAL
COLLECT_INTERVAL = 0.1      # have to wait 0.4s to collect/open the next item