"""
Game Settings and Configuration
Centralized configuration for the A3 Yasuo game project.
"""

# Display settings
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FPS = 60
FULLSCREEN = False
SCALE_FACTOR = 4 # need to scale because our backgrounds have size 320x180 => Scale 4 times
TILE_SIZE_RAW = 24
TILE_SIZE = TILE_SIZE_RAW * SCALE_FACTOR # this is the standard unit we use to do other works later
# so we have 7.5 rows => ceil to 8 rows. 7 full rows and 1/2 the last row.

# Game settings
GAME_TITLE = "A3 Yasuo - Action Game"

# Asset paths
ASSETS_PATH = "assets"
NPC_PATH = "assets/NPC"
PLAYER_PATH = "assets/Player"
MAP_PATH = "assets/Map"
SKILLS_PATH = "assets/Skills"


# NPC Settings
NPC_GHOST_HEALTH = 100
NPC_GHOST_DAMAGE = 10
NPC_GHOST_ATTACK_RANGE = 100
NPC_GHOST_SPEED = 2
NPC_GHOST_DETECTION_RANGE = 300
NPC_GHOST_PATROL_RADIUS = 200
NPC_GHOST_ATTACK_COOLDOWN = 60  # frames
NPC_GHOST_PROJECTILE_SPEED = 8

NPC_SHOOTER_HEALTH = 120
NPC_SHOOTER_DAMAGE = 5
NPC_SHOOTER_ATTACK_RANGE = 200
NPC_SHOOTER_SPEED = 1.5
NPC_SHOOTER_DETECTION_RANGE = 400
NPC_SHOOTER_PATROL_RADIUS = 150
NPC_SHOOTER_ATTACK_COOLDOWN = 40  # frames
NPC_SHOOTER_PROJECTILE_SPEED = 12

NPC_ONRE_HEALTH = 150
NPC_ONRE_DAMAGE = 8
NPC_ONRE_ATTACK_RANGE = 50
NPC_ONRE_SPEED = 2.5
NPC_ONRE_DETECTION_RANGE = 250
NPC_ONRE_PATROL_RADIUS = 180
NPC_ONRE_ATTACK_COOLDOWN = 40  # frames


# Boss Settings
BOSS_HEALTH = 3000
BOSS_SPEED = 10

BOSS_MELEE_DAMAGE = 25
BOSS_MELEE_RANGE = 300
BOSS_MELEE_COOLDOWN = 45
BOSS_MELEE_HIT_FRAME = 2

BOSS_RANGED_DAMAGE = 15
BOSS_PROJECTILE_SPEED = 15
BOSS_RANGED_COOLDOWN = 60

BOSS_LASER_DAMAGE = 40
BOSS_METEOR_DAMAGE = 80
BOSS_SKILL_COOLDOWN = 300 


# Player Settings
PLAYER_HEALTH = 200
PLAYER_SPEED_WALK = 150
PLAYER_SPEED_RUN = 300
PLAYER_JUMP_POWER = 10

# Combat Settings
ATTACK_COOLDOWN = 30
SKILL_Q_COOLDOWN = 120
SKILL_W_COOLDOWN = 180
SKILL_E_COOLDOWN = 90

# Damage Settings [MỚI]
DAMAGE_NORMAL = 20
DAMAGE_SKILL_E = 50
DAMAGE_SKILL_Q = 100
DAMAGE_SKILL_W = 30 

# Block Settings [MỚI]
BLOCK_DAMAGE_REDUCTION = 0.9
BLOCK_STAMINA_COST_PER_HIT = 20

# Player Stats (Refactored for Spec)
PLAYER_MAX_HEALTH = 200
PLAYER_MAX_STAMINA = 100

PLAYER_STAMINA_REGEN_WALK = 0.5  # Hồi nội năng khi đi bộ
PLAYER_HEALTH_REGEN = 0.02      # Hồi máu tự nhiên (nếu có)

PLAYER_RUN_COST = 0.2           # Chạy tốn stamina
SKILL_Q_COST = 20
SKILL_W_COST = 30
SKILL_E_COST = 15

# Mechanisms
PLAYER_LIFESTEAL = 100          # Hút máu toàn phần (100%)

# Cơ chế thưởng (Reward)
Reward_Hit_Stamina = 5
Reward_Kill_Stamina = 30

# Physics
GRAVITY = 0.5
MAX_FALL_SPEED = 10
GROUND_Y = 480 # Mức đất tạm thời để test di chuyển (Row 5-6 * 96)

# Colors (R, G, B, A)
COLOR_BLACK = (0, 0, 0, 255)
COLOR_WHITE = (255, 255, 255, 255)
COLOR_RED = (255, 0, 0, 255)
COLOR_GREEN = (0, 255, 0, 255)
COLOR_BLUE = (0, 0, 255, 255)
COLOR_BACKGROUND = (20, 20, 30, 255)
